= BuildXPages
Cameron Gregor <camerongregor.com>
:toc: left
:projname: BuildXPages

https://github.com/camac/BuildXPages[BuildXPages GitHub Project]

== Introduction

{projname} is a collection of tools which can aid in the Building and Deployment of XPages NSFs and XPages plugins. If you would like to automate some or all of your XPages Deployment then there might be something in here for you!

Over the past couple of years, I have developed these tools for my own use. Although the tools worked fine, there was no documentation and they were not necessarily easy to understand or use. 

I decided to spend some further time to clean it all up and write documentation so it is easily available to the rest of the community. It has taken a couple of months to get all this done, so if this actually helps anyone else I would love to hear about it so I know it was worth the effort! 

There is a good chance I have a bug here or there or have made mistakes in the documentation. In order to use this project there is a bit of setup required and everyone's environment will be slightly different.
I have tried to document as much as I can but if something is hard to understand or doesn't work as expected please let me know so I can help you figure out where the problem lies and fix any bugs or documentation.

=== What can I use BuildXPages for?

Some ideas of some tasks which this project can help you achieve

* Refreshing Database Designs
* Copying / Deleting Databases
* Configuring Database Template Inheritance
* Building NSFs from source code in an On-Disk Project
* Building Plugins and Features
* Deploying Plugins and Features to Servers
* Deploying Plugins and Features to Notes/Designer
* Starting / Stopping / Restarting Http Servers

=== What does the project provide?

There are 2 main artifacts that this project provides which is an ANT Library and a Domino Designer Plugin.

==== ANT Library of Notes/Domino related tasks

The Project contains a library of tasks that can be organised and executed by https://ant.apache.org/[Apache ANT^]. 

See the <<TasksLibrary,Documentation of the BuildXPages ANT Library>> that is provided later is this user guide for more information.

Apache ANT is a build tool which helps you write instructions on how to automate tasks. If you haven't used Ant before, don't be scared! It is pretty simple once you get the hang of it. 
Yes there are other options, but Ant is well documented which makes it easier to understand.
I have also provided some tutorials which should give you a feel for how it all works.

Ant has access to many commonly used steps such as manipluation of files in the filesystem (copy, move, delete, unzip etc.) and more complex tasks such as compiling java, running programs.

==== Headless Domino Designer Plugin

This project also includes a Plugin for Domino Designer which is used by the ANT task for building an NSF.

See the <<TasksLibrary,Documentation of the BuildXPages ANT Library>> that is provided later is this user guide for more information.

The Plugin is basically an extension of the existing 'Headless Designer' system that was provided by IBM. The IBM Headless Designer system was a great start but could have used a little bit more love. There were a few annoyances, it was hard to tell when the build was finished, it was hard to tell that the build even started properly. There were some minor annoyances regarding project names and locations. 
The mechanism also involved writing a text 'command file', which was fed in when starting designer. This means each build would always have to start designer, build and then shut it down. If designer did not shut down, then you couldn't start it up again and weird things like that.

So I decided to extend it and turn the functionality into a 'headless server'. This allow designer to remain open the whole time and listen for instructions from my ant tasks. If I need designer to restart and can tell it to shut down, and then start designer again and the 'headless server' starts again to wait for more instructions.

== Troubleshooting / Bugs / Feedback

If you have found a bug, can't understand something, want some advice then you can 
submit an Issue using the https://github.com/camac/BuildXPages/issues[Project's Github Issues page^] and I will get back to you! 

If this project is helping you out I would love to hear it as well! I'm on twitter https://twitter.com/gregorbyte[@gregorbyte^] and my blog is at https://camerongregor.com/[camerongregor.com^] you can also find me in the https://xpages-slack.herokuapp.com/[XPages Slack Community^] which you can join using that link

:leveloffset: +1

include::gettingstarted.adoc[]

:leveloffset: -1

include::tasks.adoc[]

include::headlessplugin.adoc[]

include::tutorials.adoc[]

