=== initdesignersite 

[NOTE]
====
I am not sure this is a great way to deploy plugins so  I haven't detailed this part yet.
====

This task is used to set up an update site that will always be loaded when Designer Is started up. This is only used when you are deploying plugins to Domino Designer using the sneaky 'permanent update site' method.

This task is just like the **updateDesignerLink** task, however it will create the update site folder structure within the framework directory of the Notes Installation.

You can then copy plugins to this update site, and they will be loaded by designer (if you have configured platform.xml using the **checkplatformxml** task)

==== Properties

[horizontal]
notesProgDir:: The Notes Program Directory on this machine

==== Attributes

[horizontal]
updateSiteLabel:: This is a short code to be used as a name for the update site. It will be used in a filename so it should be something simple e.g. 'extlib'

==== Example

include::../com.gregorbyte.buildxpages.ant/buildTest.xml[tag=updatedesignerlink]