== Building Features and Plugins

In this Demonstration we build a plugin by doing a Headless Eclipse feature build.

The general way this works is, you create a feature that lists the plugins that you want to build. You then tell eclipse (via a command line instruction) to build this feature, and it will build each plugin and package it up for you.

BuildXPages has a task *buildfeature* which basically just helps issue the command line instruction.

This is a very short demonstration, as I am not very sure there is a very big audience for this.
Hopefully this demonstration will give you an idea of how it works but if you need to know more please feel free to ask me questions about it.

If you want to learn more about the headless eclipse works, then check out the following link https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_feature_build.htm[Automated building of Features]

[IMPORTANT]
====
Make sure you have performed the necessary setup as in the getting started section
====

=== Building the Plugin/Feature

The *demo/buildfeature* directory contains the source code of a plugin, and also a feature.

* com.gregorbyte.buildxpages.demo
* com.gregorbyte.buildxpages.demo.feature

We are going to execute the *build* target, lets have a look at it

[source,xml]
----
include::../demo/buildfeature/build.xml[tag=build]
----

The eclipse headless build performs all it's operations in a 'build directory' which is basically like a working area, so before running a build, we have to prepare this build directory and make sure it has plugins and features we need to build. 

We do this using buildxpages *copytobuilddir* task which copies a plugin or a feature to the build directory. The *copytobuilddir* expects there to be a *buildDir* set which specifieds the build directory location.

We then use buildxpages *buildfeature* task to trigger the build, and we specify the feature that we are building. 

1. Open your console and navigate to the demo/buildfeature folder
2. Type `ant`

You should then see some output like so:

[source,txt]
----
Buildfile: V:\Projects\BuildXPages\demo\buildfeature\build.xml

clean:
   [delete] Deleting directory V:\Projects\BuildXPages\demo\buildfeature\buildDirectory

init:
    [mkdir] Created dir: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory
    [mkdir] Created dir: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\plugins
    [mkdir] Created dir: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features

build:
     [copy] Copying 7 files to V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\plugins\com.gregorbyte.buildxpages.demo
     [copy] Copying 3 files to V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature
     [echo] Init Default Properties
     [java] org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
     [java] Starting Groovy-Eclipse compiler resolver.  Specified compiler level: unspecified
     [java] 850 2.3.7.xx-201411061335-e44-RELEASE = STARTING
     [java] org.eclipse.m2e.logback.configuration: Logback config file: V:\Cameron\workspace\.metadata\.plugins\org.eclipse.m2e.logback.configuration\logback.1.5.1.20150109-1820.xml
     [java] org.eclipse.m2e.logback.configuration: Initializing logback
     [java] Unknown argument: -DpluginPath=
     [java] Buildfile: C:/eclipse-luna/eclipse/plugins/org.eclipse.pde.build_3.9.0.v20140415-2029/scripts/build.xml
     [java] 
     [java] main:
     [java] 
     [java] preBuild:
     [java] 
----

And then a lot more of that kind of stuff and finally, hopefully you see the BUILD SUCCESSFULL message

[source,txt]
----
     [java] gather.logs:
     [java]     [mkdir] Created dir: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature\feature.temp.folder\plugins\com.gregorbyte.buildxpages.demo_1.0.0.201709212144
     [java]      [copy] Copying 1 file to V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature\feature.temp.folder\plugins\com.gregorbyte.buildxpages.demo_1.0.0.201709212144
     [java] 
     [java] update.feature:
     [java] 
     [java] all.children:
     [java]       [zip] Building zip: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature\com.gregorbyte.buildxpages.demo.feature_1.0.0.201709212144.log.zip
     [java]    [delete] Deleting directory V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature\feature.temp.folder
     [java]     [unzip] Expanding: V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\features\com.gregorbyte.buildxpages.demo.feature\com.gregorbyte.buildxpages.demo.feature_1.0.0.201709212144.log.zip into V:\Projects\BuildXPages\demo\buildfeature\buildDirectory\BuildXPagesDemo\compilelogs
     [java] BUILD SUCCESSFUL
     [java] 
     [java] BUILD SUCCESSFUL
     [java] Total time: 3 seconds

BUILD SUCCESSFUL
Total time: 5 seconds
----

After the build is finished you should see (among other things) a zip file in the *demo/buildfeature/buildDirectory/BuildXPagesDemo* directory. This zip file contains the plugins and features that were built!

=== Conclusion

So this was a short demo of building a plugin using headless eclipse. The next demonstration tutorial shows how we can take these plugins and deploy them somewhere


