== Deploying an NSF

Once you have built an NSF, you may want to deploy the latest changes to it's target environment.

There is more than one way to deploy an NSF, not everyone is going to do it the same way. This tutorial will hopefully demonstrate some of the tasks you could use to acheive your desired deployment.

This tutorial assumes that you have successfully completed the Build An NSF tutorial. In this case you will have an NSF in your local workspace. We are going to deploy this NSF.

=== Basic File-Level Copying

At the most basic Level, you may have built your NSF directly to a local Notes workspace, and just want to copy the *.nsf* file to another location. In this case you would just use a simple Apache Ant copy task.

In this example, we are going to copy the NSF that you built into a local directory

=== Copying an NSF using Notes/Domino

Instead of doing basic file-based copying, we can actually use IBM Notes to copy an NSF from our local workspace to a server, or from one server to another server etc.

To do this we use BuildXPages' *copynsf* task.

We are going to create 2 copies of this NSF just so we can use them both in our next example



=== Setting up template names

BuildXPages has a *settemplatenames* task which is useful for configuring template inheritance dynamically. 


=== Refreshing a Template

When you are ready to refresh teh design of a database, you can simple use the *refreshdbdesign* task.

What is handy about this is that you can refresh the design of a target nsf using an NSF from your local workspace. So, if you have built an NSF in your local workspace you can refresh an NSF on a server using the design on your local workspace.



=== Deleting NSFs

If you have a need to delete nsfs during your deployment process, you can use the *deletensf* task

This is my preferred option.

* I have 'local' nsfs located on the headless build machine
* I have a Production Template
* I have one or more Production Applications

I set the 'master template' name of the built nsf, and the inherit of the template
I refresh the production template
I either allow the design task to run overnight, or if doing an immediate deployment, I issue the load design task console command
